package com.vjaykrsna.nanoai.core.model

/**
 * Source/origin of an assistant message response.
 * Indicates whether the response was generated locally or via cloud API.
 */
enum class MessageSource {
    /**
     * Response generated by on-device local model (e.g., MediaPipe, TFLite).
     */
    LOCAL_MODEL,

    /**
     * Response generated by cloud API (e.g., OpenAI, Gemini via gateway).
     */
    CLOUD_API,
}
