@file:Suppress("MagicNumber")

package com.vjaykrsna.nanoai.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme
val LightPrimary = Color(0xFF4F46E5)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFE0E7FF)
val LightOnPrimaryContainer = Color(0xFF1E1B4B)
val LightSecondary = Color(0xFF475569)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFDDE4F5)
val LightOnSecondaryContainer = Color(0xFF101B2D)
val LightTertiary = Color(0xFF0EA5E9)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFCFFAFE)
val LightOnTertiaryContainer = Color(0xFF022C3A)
val LightBackground = Color(0xFFF8FAFC)
val LightOnBackground = Color(0xFF0F172A)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF0F172A)
val LightSurfaceVariant = Color(0xFFE2E8F0)
val LightOnSurfaceVariant = Color(0xFF475569)
val LightOutline = Color(0xFF94A3B8)
val LightOutlineVariant = Color(0xFFD0D7E5)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightInverseSurface = Color(0xFF1E293B)
val LightInverseOnSurface = Color(0xFFE2E8F0)
val LightInversePrimary = Color(0xFFC7D2FE)

// Dark scheme
val DarkPrimary = Color(0xFFC7D2FE)
val DarkOnPrimary = Color(0xFF1E1B4B)
val DarkPrimaryContainer = Color(0xFF3730A3)
val DarkOnPrimaryContainer = Color(0xFFE0E7FF)
val DarkSecondary = Color(0xFFBAC7E5)
val DarkOnSecondary = Color(0xFF1B2637)
val DarkSecondaryContainer = Color(0xFF2F3A4F)
val DarkOnSecondaryContainer = Color(0xFFDDE4F5)
val DarkTertiary = Color(0xFF7DD3FC)
val DarkOnTertiary = Color(0xFF003547)
val DarkTertiaryContainer = Color(0xFF03557C)
val DarkOnTertiaryContainer = Color(0xFFCFFAFE)
val DarkBackground = Color(0xFF0F172A)
val DarkOnBackground = Color(0xFFE2E8F0)
val DarkSurface = Color(0xFF111827)
val DarkOnSurface = Color(0xFFDDE3F0)
val DarkSurfaceVariant = Color(0xFF2F3A4F)
val DarkOnSurfaceVariant = Color(0xFFBAC7E5)
val DarkOutline = Color(0xFF8090AD)
val DarkOutlineVariant = Color(0xFF2F3A4F)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkInverseSurface = Color(0xFFE2E8F0)
val DarkInverseOnSurface = Color(0xFF0F172A)
val DarkInversePrimary = Color(0xFF4F46E5)
