openapi: 3.1.0
info:
  title: nanoAI Cloud Gateway API
  version: 0.1.0
servers:
  - url: https://{tenant}.nanoai.app/api
    variables:
      tenant:
        default: default
paths:
  /v1/completions:
    post:
      summary: Proxy completion requests to configured providers (OpenAI-compatible schema)
      operationId: createCompletion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - model
                - messages
              properties:
                model:
                  type: string
                  description: Provider-specific model key (e.g., gpt-4o-mini, gemini-pro).
                messages:
                  type: array
                  items:
                    type: object
                    required:
                      - role
                      - content
                    properties:
                      role:
                        type: string
                        enum: [system, user, assistant]
                      content:
                        type: string
                temperature:
                  type: number
                  minimum: 0
                  maximum: 2
                  default: 0.7
                top_p:
                  type: number
                  minimum: 0
                  maximum: 1
                  default: 1
                max_tokens:
                  type: integer
                  minimum: 1
                  maximum: 8192
                stream:
                  type: boolean
                  default: false
                metadata:
                  type: object
                  description: Provider-specific options (e.g., Gemini safety settings).
      responses:
        '200':
          description: Provider response normalized to OpenAI schema
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - created
                  - choices
                properties:
                  id:
                    type: string
                  created:
                    type: integer
                  model:
                    type: string
                  choices:
                    type: array
                    items:
                      type: object
                      required:
                        - index
                        - message
                        - finish_reason
                      properties:
                        index:
                          type: integer
                        message:
                          type: object
                          required:
                            - role
                            - content
                          properties:
                            role:
                              type: string
                              enum: [assistant]
                            content:
                              type: string
                        finish_reason:
                          type: string
                  usage:
                    type: object
                    properties:
                      prompt_tokens:
                        type: integer
                      completion_tokens:
                        type: integer
                      total_tokens:
                        type: integer
        '401':
          description: Invalid credentials for downstream provider
        '429':
          description: Provider rate limit exceeded
        '502':
          description: Provider unreachable or malformed response
      security:
        - ApiKeyAuth: []
  /v1/models:
    get:
      summary: List available provider models and metadata
      operationId: listModels
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      required:
                        - id
                        - provider
                      properties:
                        id:
                          type: string
                        provider:
                          type: string
                        capabilities:
                          type: array
                          items:
                            type: string
                        input_formats:
                          type: array
                          items:
                            type: string
                        output_formats:
                          type: array
                          items:
                            type: string
                        context_window:
                          type: integer
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
