@file:Suppress("MagicNumber")

package com.vjaykrsna.nanoai.shared.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme
val LightPrimary = Color(0xFF4F46E5)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFE0E7FF)
val LightOnPrimaryContainer = Color(0xFF1E1B4B)
val LightSecondary = Color(0xFF475569)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFDDE4F5)
val LightOnSecondaryContainer = Color(0xFF101B2D)
val LightTertiary = Color(0xFF0EA5E9)
val LightOnTertiary = Color(0xFF001F29)
val LightTertiaryContainer = Color(0xFFCFFAFE)
val LightOnTertiaryContainer = Color(0xFF022C3A)
val LightBackground = Color(0xFFF8FAFC)
val LightOnBackground = Color(0xFF0F172A)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF0F172A)
val LightSurfaceVariant = Color(0xFFE2E8F0)
val LightOnSurfaceVariant = Color(0xFF334155)
val LightOutline = Color(0xFF94A3B8)
val LightOutlineVariant = Color(0xFFD0D7E5)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightInverseSurface = Color(0xFF1E293B)
val LightInverseOnSurface = Color(0xFFE2E8F0)
val LightInversePrimary = Color(0xFFC7D2FE)

// Dark scheme
val DarkPrimary = Color(0xFFC7D2FE)
val DarkOnPrimary = Color(0xFF1E1B4B)
val DarkPrimaryContainer = Color(0xFF3730A3)
val DarkOnPrimaryContainer = Color(0xFFE0E7FF)
val DarkSecondary = Color(0xFFBAC7E5)
val DarkOnSecondary = Color(0xFF1B2637)
val DarkSecondaryContainer = Color(0xFF2F3A4F)
val DarkOnSecondaryContainer = Color(0xFFDDE4F5)
val DarkTertiary = Color(0xFF7DD3FC)
val DarkOnTertiary = Color(0xFF003547)
val DarkTertiaryContainer = Color(0xFF03557C)
val DarkOnTertiaryContainer = Color(0xFFCFFAFE)
val DarkBackground = Color(0xFF0F172A)
val DarkOnBackground = Color(0xFFE2E8F0)
val DarkSurface = Color(0xFF111827)
val DarkOnSurface = Color(0xFFDDE3F0)
val DarkSurfaceVariant = Color(0xFF2F3A4F)
val DarkOnSurfaceVariant = Color(0xFFBAC7E5)
val DarkOutline = Color(0xFF8090AD)
val DarkOutlineVariant = Color(0xFF2F3A4F)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkInverseSurface = Color(0xFFE2E8F0)
val DarkInverseOnSurface = Color(0xFF0F172A)
val DarkInversePrimary = Color(0xFF4F46E5)

// AMOLED colors for power saving on AMOLED displays
val AmoledBackground = Color(0xFF000000)
val AmoledSurface = Color(0xFF000000)
val AmoledSurfaceVariant = Color(0xFF0A0A0A)

// High contrast light scheme (WCAG AAA compliant)
val HighContrastLightPrimary = Color(0xFF0A0066) // Deep blue-purple, high contrast
val HighContrastLightOnPrimary = Color(0xFFFFFFFF)
val HighContrastLightPrimaryContainer = Color(0xFFE0E7FF)
val HighContrastLightOnPrimaryContainer = Color(0xFF0A0066)
val HighContrastLightSecondary = Color(0xFF1B1B1B) // Near-black
val HighContrastLightOnSecondary = Color(0xFFFFFFFF)
val HighContrastLightSecondaryContainer = Color(0xFFE8E8E8)
val HighContrastLightOnSecondaryContainer = Color(0xFF1B1B1B)
val HighContrastLightTertiary = Color(0xFF004D7A) // Deep teal
val HighContrastLightOnTertiary = Color(0xFFFFFFFF)
val HighContrastLightTertiaryContainer = Color(0xFFCFFAFE)
val HighContrastLightOnTertiaryContainer = Color(0xFF004D7A)
val HighContrastLightBackground = Color(0xFFFAFAFA)
val HighContrastLightOnBackground = Color(0xFF000000)
val HighContrastLightSurface = Color(0xFFFFFFFF)
val HighContrastLightOnSurface = Color(0xFF000000)
val HighContrastLightSurfaceVariant = Color(0xFFCCCCCC)
val HighContrastLightOnSurfaceVariant = Color(0xFF1B1B1B)
val HighContrastLightOutline = Color(0xFF333333)
val HighContrastLightOutlineVariant = Color(0xFF666666)
val HighContrastLightError = Color(0xFF8B0000) // Dark red
val HighContrastLightOnError = Color(0xFFFFFFFF)
val HighContrastLightErrorContainer = Color(0xFFFFDAD6)
val HighContrastLightOnErrorContainer = Color(0xFF8B0000)
val HighContrastLightInverseSurface = Color(0xFF1B1B1B)
val HighContrastLightInverseOnSurface = Color(0xFFFAFAFA)
val HighContrastLightInversePrimary = Color(0xFFE0E7FF)

// High contrast dark scheme (WCAG AAA compliant)
val HighContrastDarkPrimary = Color(0xFFCCE5FF) // Very light blue
val HighContrastDarkOnPrimary = Color(0xFF000000)
val HighContrastDarkPrimaryContainer = Color(0xFF0A0066)
val HighContrastDarkOnPrimaryContainer = Color(0xFFE0E7FF)
val HighContrastDarkSecondary = Color(0xFFF0F0F0) // Very light gray
val HighContrastDarkOnSecondary = Color(0xFF000000)
val HighContrastDarkSecondaryContainer = Color(0xFF333333)
val HighContrastDarkOnSecondaryContainer = Color(0xFFF0F0F0)
val HighContrastDarkTertiary = Color(0xFFA8DAFF) // Bright cyan
val HighContrastDarkOnTertiary = Color(0xFF000000)
val HighContrastDarkTertiaryContainer = Color(0xFF004D7A)
val HighContrastDarkOnTertiaryContainer = Color(0xFFA8DAFF)
val HighContrastDarkBackground = Color(0xFF000000)
val HighContrastDarkOnBackground = Color(0xFFFAFAFA)
val HighContrastDarkSurface = Color(0xFF050505)
val HighContrastDarkOnSurface = Color(0xFFFAFAFA)
val HighContrastDarkSurfaceVariant = Color(0xFF333333)
val HighContrastDarkOnSurfaceVariant = Color(0xFFE8E8E8)
val HighContrastDarkOutline = Color(0xFFCCCCCC)
val HighContrastDarkOutlineVariant = Color(0xFF999999)
val HighContrastDarkError = Color(0xFFFF6B6B) // Bright red
val HighContrastDarkOnError = Color(0xFF000000)
val HighContrastDarkErrorContainer = Color(0xFF8B0000)
val HighContrastDarkOnErrorContainer = Color(0xFFFF9999)
val HighContrastDarkInverseSurface = Color(0xFFFAFAFA)
val HighContrastDarkInverseOnSurface = Color(0xFF000000)
val HighContrastDarkInversePrimary = Color(0xFF0A0066)
